services:
  metaduck:
    build:
      context: .
      dockerfile: Dockerfile
    image: metaduck:latest
    container_name: metaduck
    ports:
      - "8083:3000"   # Use port 8081
    environment:
      # tell Metabase to use this file for its own metadata
      MB_DB_FILE: /metabase-data/metabase.db
      # where Metabase will look for plugins
      MB_PLUGINS_DIR: /home/plugins
      JAVA_TOOL_OPTIONS: "-Djava.library.path=/home/plugins"
    # limit container to 2GB RAM
    mem_limit: 2g
    volumes:
      - ./metabase_data:/metabase-data  # host‐persisted metadata
      - ./data:/data

volumes:
  metabase_data:
